"""Navigation abstraction to isolate web automation implementation."""

from __future__ import annotations

from typing import Protocol, Sequence

from .models import AppointmentSlot


class BrowserNavigator(Protocol):
    """Port interface to automate browser actions."""

    def open(self, url: str, timeout_seconds: int) -> None: ...

    def wait_page_ready(self) -> None: ...

    def fill_personal_data(self, *, document_id: str, full_name: str, postal_code: str, phone: str, email: str) -> None: ...

    def get_options(self, field_key: str) -> Sequence[str]: ...

    def choose_option(self, field_key: str, value: str) -> None: ...

    def has_linked_procedure_prompt(self) -> bool: ...

    def choose_linked_procedure(self, option: str) -> None: ...

    def get_available_slots(self) -> Sequence[AppointmentSlot]: ...

    def choose_slot(self, slot: AppointmentSlot) -> None: ...

    def submit(self) -> None: ...

    def session_expired(self) -> bool: ...

    def captcha_or_official_auth_required(self) -> bool: ...
